version: '3'

services:
    great_edu_web:
        container_name: great_edu_web
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/src
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        depends_on:
            - great_edu_php


    great_edu_php:
        container_name: great_edu_php
        # image: php:fpm
        build:
            context: src
            dockerfile: Dockerfile
        volumes:
            - ./src:/src
        networks:
            - code-network
        depends_on:
            - great_edu_mysql


    great_edu_mysql:
        container_name: great_edu_mysql
        image: mysql
        command: mysqld --default-authentication-plugin=mysql_native_password
        # volumes:
        #   - ./data:/var/lib/mysql
        restart: on-failure
        volumes:
        - ./dumps:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        ports:
            - '33315:3306'
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
